// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Models;

#nullable disable

namespace WeatherApp.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20221011110822_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WeatherApp.Models.Weather", b =>
                {
                    b.Property<int>("WeatherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherID"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("WeatherID");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            WeatherID = -1,
                            City = "Lisboa",
                            Date = "2022-10-01",
                            Temperature = 12.0
                        },
                        new
                        {
                            WeatherID = -2,
                            City = "Lisboa",
                            Date = "2022-10-02",
                            Temperature = 14.0
                        },
                        new
                        {
                            WeatherID = -3,
                            City = "Lisboa",
                            Date = "2022-10-03",
                            Temperature = 16.0
                        },
                        new
                        {
                            WeatherID = -4,
                            City = "Lisboa",
                            Date = "2022-10-04",
                            Temperature = 18.0
                        },
                        new
                        {
                            WeatherID = -5,
                            City = "Lisboa",
                            Date = "2022-10-05",
                            Temperature = 14.0
                        },
                        new
                        {
                            WeatherID = -6,
                            City = "Lisboa",
                            Date = "2022-10-06",
                            Temperature = 6.0
                        },
                        new
                        {
                            WeatherID = -7,
                            City = "Lisboa",
                            Date = "2022-10-07",
                            Temperature = 11.0
                        },
                        new
                        {
                            WeatherID = -8,
                            City = "Lisboa",
                            Date = "2022-10-08",
                            Temperature = 22.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
